### ISSUE TITLE
spleeter-native FFMPEG error: no such file or directory

### ISSUE THREAD

**Issue by nedimhaveric** [diracdeltas/spleeter4max#34]
**Did you read the installation instructions already?** 

Yes

**Describe the issue**

Spleeter runs and opens the newly  created file for the stems. 
No tracks in folder. 
Folder is empty 

**Max Console Screenshots**

![image](https://user-images.githubusercontent.com/22703277/84352900-29022900-ab8c-11ea-9efe-bf9314636544.png)

![image](https://user-images.githubusercontent.com/22703277/84352948-3a4b3580-ab8c-11ea-84d2-22105db3f6f4.png)

**Info:**
 - spleeter-native
 - OS: Windows
 - Ableton version 10.1.14
 - Max version 8.1.3

**Comment by diracdeltas** [comment]
at a glance, seems like the issue might be that ffmpeg doesn't have permission to access the files in `D:\\Program Files`. you could try moving the entire spleeter-native directory to a different folder (like somewhere in home). or you could enable spleeter/ffmpeg to run as admin, though offhand i'm not sure how to do that because i don't use windows.

another is to just use the spleeter docker install instead of spleeter-native, assuming your version of windows supports docker.

**Comment by nedimhaveric** [comment]
Seems that part of issue was that the INPUT FILE name was too long.

After shortening new error appeared: [winerror5] access is denied

Attempted to fix by running command prompt as admin and running pip install pydictionary
error persisted

if anyone can point me in the write direction please do
not sure which program is supposed to have permission or even what permission it needs

![1](https://user-images.githubusercontent.com/22703277/84455302-fe1ae200-ac2a-11ea-9a81-ea9b444f7c45.png)
![2](https://user-images.githubusercontent.com/22703277/84455304-ffe4a580-ac2a-11ea-9854-51737b53a3f0.png)

**Comment by diracdeltas** [comment]
does this help? https://github.com/diracdeltas/spleeter4max/issues/7

**Comment by diracdeltas** [comment]
if not you may have to aslso enable run as administrator on python itself and maybe also ffmpeg

**Comment by nedimhaveric** [comment]
After following the instructions in #7 it worked without a hitch!

Thanks for all the help! <3

**Comment by diracdeltas** [comment]
awesome!
